### ISSUE TITLE
Permitir contribuição de usuários

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#1]
Possibilitar que usuários possam contribuir com informações faltantes em imagens e vídeos. Podem ser alterados apenas os seguintes campos:
Título; Autor(es) da imagem/vídeo; País; Estado; Cidade; Bairro; Endereço;Data da imagem; Autor(es) da obra; Ano de conclusão da obra; e Descrição.

Para esta versão os seguintes campos ainda NÃO podem ser alterados: Imagem ou vídeo; Tags; Álbum; e Licença.

A alteração de dados é permitida apenas para imagens de usuários comuns. As imagens de acervos institucionais só podem ser alteradas por membros dos acervos.

Fluxo: Usuário acessa a página de visualização de dados da imagem ou vídeo. Abaixo dos campos com dados da imagem apresentar um Banner com o seguinte label:
Você conhece mais informações sobre esta arquitetura? (Título); com o seguinte subtítulo: Nós precisamos saber ... (campos faltantes da imagem selecionada). Por exemplo: Nós precisamos saber a data de conclusão da obra e quem são os autores? Botão com label: Conheço!

**Comment by anapaula** [comment]
Quando usuário clica em botão Conheço sem estar logado, deveria ser encaminhado para tela de login.

**Comment by anapaula** [comment]
O próprio autor da imagem não é encaminhado para o fluxo de imagens. Caso o autor da imagem clique no botão (Conheço) para abertura dos cartões para Sugestão/Confirmação será encaminhado para a tela de edição da imagem.

**Comment by anapaula** [comment]
O botão de abertura dos cartões para Sugestão/Confirmação de dados só deve ser exibido para imagens de usuários comuns, o que inclui também os vídeos. Portanto, para fotos de instituições não será apresentado o botão para visualização dos cartões.

**Comment by anapaula** [comment]
Os usuários institucionais conseguem visualizar o botão (Conheço) de abertura dos cartões para Sugestão/Confirmação apenas nas imagens de usuários comuns.

**Comment by joaohkfaria** [comment]
@anapaula Acho que seria melhor ter aberto as issues separadas, porque não consigo responder cada um dos seus comentários.

1) já está feito agora.
2) Ele já vai pra edição da imagem quando é o usuário da foto. Aqui está funcionando isso
3) Para instituições já estava feito. Preciso fazer para vídeos, mas existe um bug pra adicionar videos aqui.
4) Porque um usuário institucional não poderia contribuir com uma foto que não é dele?

**Comment by anapaula** [comment]
@joaohkfaria os 4 itens estão funcionando no Mozilla e Chrome, mas não funcionam no IE 11 e Chromium.
Sobre o item 4, o usuário institucional pode contribuir com uma foto de usuário comum, mas continua valendo a mesma regra de não exibir os cartões para fotos de usuários institucionais.

**Comment by joaohkfaria** [comment]
No IE11 realmente não tenho como testar. Mas no Chromium eu testei e funcionou perfeitamente. 

Depois você testa com a nova versão e confirma se no Chromium está funcionando.
Vale também abrir o console e ver o que pode estar acontecendo.
