### ISSUE TITLE
Integrar backend-frontend de confirmação de dados

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#12]
Integrar backend para a parte de confirmação de dados já preenchidos pelo dono da imagem.
Incluir array para cards de confirmação conforme modelo:

[
{
  type: 'confirm' ou 'suggestion',
  name: 'Artigas' ou 'Autor da Obra',
  question: 'Este autor está correto?', 'Qual o autor desta obra?',
  attribute_type: 'street', 'author_name'...
  field_type: 'date', 'number', 'string'
}
]

**Comment by joaohkfaria** [comment]
Implementado no commit https://github.com/NAWEB-USP/Arquigrafia-Laravel/commit/01a37620e7ad67c2b01ebb5b6b0a3a832d105255
