### ISSUE TITLE
Formato de Arrays na abertura de cards

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#13]
Inserir formato de Arrays no botão de abertura dos cards e incluir questão para botão Não (questão padrão: Qual é a informação correta para nome_campo?)

**Comment by joaohkfaria** [comment]
Implementado no commit https://github.com/NAWEB-USP/Arquigrafia-Laravel/commit/be5a407aa273ce83b3b31933d00a4795ebb9e16d
