### ISSUE TITLE
Barra de progresso de dados da foto

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#19]
Na versão gamificada, o usuário visualiza na página de uma imagem selecionada, uma barra de progresso que indica a porcentagem de completude de dados desta imagem. 

Quando usuário sugere um dado para um campo, enquanto o dado não for avaliado por um moderador, a barra de progresso marca em cor diferente que o dado sugerido será avaliado e apenas muda para cor que indica completude quando o dado tiver sido avaliado por moderador do sistema. Sugestão de cores para barra de progresso:
Cinza escuro para dado confirmado, cinza claro para dado em revisão e branco para porcentagem de dados ainda não preenchidos.

**Comment by joaohkfaria** [comment]
Implementado no commit https://github.com/NAWEB-USP/Arquigrafia-Laravel/commit/f356b34a1a89281919106c7f4d0dedb6cad85b14
