### ISSUE TITLE
Fluxo para questões e respostas sobre as imagens

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#2]
Após usuário clicar em botão Conheço na questão 'Você conhece mais informações sobre esta arquitetura?', da issue #1, será encaminhado para um fluxo de cartões com questões sobre a imagem ou vídeo que está visualizando.

As questões serão específicas por campo com prioridade para o campo Autor da obra. Se este estiver faltando é o primeiro a ser apresentado. Todos os demais campos serão exibidos em cartões diferentes randomicamente. Por exemplo, um cartão pode conter a seguinte questão: Quem são os autores da obra? Com um campo para inserir autores e o botão Enter para enviar os dados. A opção Não sei (pula para a próxima questão). As duas opções registram o dado e passam para a próxima informação faltante da imagem. Para atender à edição de dados da imagem, o fluxo de exibição dos cartões também inclui os campos que já foram preenchidos para validação dos mesmos.

Nesse caso, será necessário intercalar questões para campos faltantes com edição de dados já preenchidos. Por exemplo: Artigas é o autor desta obra? Opções: Sim, Não, Não sei. Caso não, campo para responder o valor correto é necessário. Ao selecionar passa para o próximo campo faltante ou próxima validação de campo já preenchido.

Em qualquer momento, o usuário pode fechar o fluxo de questões e os dados já respondidos precisam ser armazenados para serem enviados para moderadores avaliarem.

**Comment by joaohkfaria** [comment]
As duas opções viáveis para apresentar o modal dos cartões são:
* Tingle
https://robinparisi.github.io/tingle/
- Vantagem: Não tem nenhuma dependência
- Desvantagem: Não tem nada feito para um fluxo de cards

* jBox
https://stephanwagner.me/jBox
- Vantagem: Já tem um modelo pronto para cards.
- Desvantagem: Requer jQuery, nossa versão está muito antiga. Precisa de atualização.

Estou analisando o impacto de cada uma.

**Comment by joaohkfaria** [comment]
Decidido pelo jBox! Aplicado na branch update-jquery3
