### ISSUE TITLE
Alterar label botão Conheço para usuários não logados

### ISSUE THREAD

**Issue by anapaula** [NAWEB-USP/Arquigrafia-Laravel#24]
Quando usuário acessa a página de visualização da foto sem estar logado, visualizará o botão banner com o seguinte label “Faça o login e contribua com mais informações sobre esta imagem!”. Ao clicar sobre o banner será encaminhado para tela de login. Após o login, o usuário retorna para a página de visualização da foto que estava acessando.

**Comment by joaohkfaria** [comment]
Feito!
